# project name
project_name: "UnderwaterImageEnhancement"
run_name: "exp1"

# dataset settings
dataset_root: "/data_hdd2/users/ZhouHeng/Data/UIE/EUVP_Dataset/"
paired: True
height: 256
width: 256

# model settings
pre_trained: False
# when 'pre_trained' is true, 'pre_weight' should be given
pre_weight: None
save_path: "/data_hdd2/users/ZhouHeng/Data/UIE/EUVP_Dataset/Output/"


# common settings
num_epoch: 100
batch_size: 24
lr: 0.05
lr_b1: 0.5
lr_b2: 0.99
lambda_1: 0.3
lambda_2: 0.7
gamma: 0.5
step_size: 20
validate_interval: 10
